style: format log time in RFC3339
rhobs/monitoring-stack-operator pull request #134
Opened 2022-05-13 12:48 UTC by tremes

Format log timestamp in the RFC3339

2022-05-13 14:10 UTC, jan--f requested changes
Can you please give a before/after example of the resulting timestamps in the commit message? I imagine that motivates the change sufficiently...?

2022-05-16 01:14 UTC, sthaha submitted a review, later dismissed

2022-05-16 01:18 UTC, sthaha commented
Prints 
```
2022-05-13T13:23:10Z	INFO	controller.monitoringstack	Starting EventSource	{"reconciler group": "monitoring.rhobs", "reconciler kind": "MonitoringStack", "source": "kind source: *v1.PodDisruptionBudget"}

```
As opposed to current

```
1.6523301588633049e+09	INFO	monitoring-stack-operator	Updating stack component	{"Stack": "e2e-tests/empty-stack", "Component": "Role.rbac.authorization.k8s.io/v1", "Name": "empty-stack-prometheus"}
```

2022-05-16 01:39 UTC, sthaha commented
@tremes Thank you for the patch, quite useful! 
I agree with Jan, that it is best to document the motivation in the commit message 👼 .

2022-05-16 05:56 UTC, tremes commented
@sthaha Thanks for the snippets. I was about to add them. Yeah the motivation is to have human readable time format.

2022-05-16 06:45 UTC, sthaha commented
@tremes , I think the suggestion was to amend the commit to add those.

2022-05-16 06:55 UTC, tremes commented
@sthaha Sorry. Reading too quick....is that better now pls?

2022-05-17 00:05 UTC, sthaha approved these changes

2022-05-17 00:06 UTC, merged